
app:
  identity:
    services.url: https://identitybts.webex.com
    broker.url: https://idbrokerbts.webex.com
    subscription.url: https://identitybts.webex.com/identity/config/v2/notification
    user.scope: Identity:Config Identity:SCIM cjp:organization
  access:
    token.uri: /idb/oauth2/v1/access_token
    token.validate.uri: /idb/oauth2/v1/tokeninfo
  revoke.token.uri: /idb/oauth2/v1/revoke
  saml2.bearer.token.uri: /idb/token/v1/actions/GetBearerToken/invoke
  verification.key.uri : /idb/oauth2/v1/keys/verification
  decryption.key.uri : /idb/oauth2/v1/keys/decryption
  resource:
    id: R394f1a30049c5e118ff6037fb584a10377ffbfa98a04ea125305c8501f1783de
    secret: fa60f50fe19b5dc3382efae39cdfe192cbf8022726391a4301c2f643a96860bc
  client:
    id: Cb156047667962a2ac74db05d96280a82fd4a499e51395fe4ab8f779daff8c8e6
    secret: d66a0ea97cc48fc6c58fd22336e24380b81ae4565fa5ab5144a231996e5916de
    token.scope: Identity:SCIM Identity:OAuthKeyService Identity:Config Identity:Organization cjp:user cjp:organization

#CF CONFIGURATION
cf:
  deployment:
    type: devus1

